name: Relese workflow

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2.3.5

    - name: Set up Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Publish package to npm registry
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        yarn publish --access public

    - name: Set up Node.js environment for publishing to GitHub registry
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 14.x
        registry-url: 'https://npm.pkg.github.com'

    - name: Publish package
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
